version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      # Install required packages (Amazon Linux uses yum)
      - yum update -y && yum install -y bc unzip wget
      
      # Install Terraform
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      
      # Install tflint
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      
      # Install Go dependencies for tests
      - go -C infra mod download

  pre_build:
    commands:
      - echo "Running Terraform quality checks..."
      
      # Terraform formatting check
      - terraform -chdir=infra fmt -recursive
      - terraform -chdir=infra fmt -check -recursive
      
      # Terraform validation (without backend)
      - terraform -chdir=infra init -backend=false
      - terraform -chdir=infra validate
      
      # TFLint
      - (cd infra && tflint --init)
      - (cd infra && tflint)

  build:
    commands:
      - echo "Running Terraform tests..."
      
      # Run unit tests with coverage (short mode to skip slow checks)
      - CI_SKIP_TERRATEST=1 go -C infra test -v -short -coverprofile=coverage.out ./tests/
      - go -C infra tool cover -func=coverage.out
      
      # Check coverage threshold (60%)
      - |
        COVERAGE=$(go -C infra tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Coverage: $COVERAGE%"
        if [ $(echo "$COVERAGE < 60" | bc -l) -eq 1 ]; then
          echo "Coverage $COVERAGE% is below required 60%"
          exit 1
        fi
        echo "Coverage $COVERAGE% meets requirement"

  post_build:
    commands:
      - echo "Running Terraform plan and apply..."
      
      # Create Lambda deployment package
      - (cd web/lambda && zip -r ../../infra/lambda.zip .)
      
      # Initialize Terraform backend (required for each phase)
      - terraform -chdir=infra init -reconfigure
      
      # Terraform plan
      - terraform -chdir=infra plan -out=tfplan
      
      # Terraform apply (only if not a PR)
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_CREATED" ] || [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_UPDATED" ]; then
          echo "Skipping apply for pull request"
        else
          # Apply Terraform
          terraform -chdir=infra apply -auto-approve tfplan
          
          # Get the CodeBuild role name from the current execution context
          CODEBUILD_ROLE_ARN=$(aws sts get-caller-identity --query 'Arn' --output text)
          CODEBUILD_ROLE_NAME=$(echo $CODEBUILD_ROLE_ARN | cut -d'/' -f2)
          ADDITIONAL_POLICY_ARN=$(terraform -chdir=infra output -raw codebuild_additional_policy_arn)
          
          echo "CodeBuild Role: $CODEBUILD_ROLE_NAME"
          echo "Policy ARN: $ADDITIONAL_POLICY_ARN"
          
          # Check if policy is already attached
          if aws iam list-attached-role-policies --role-name "$CODEBUILD_ROLE_NAME" --query 'AttachedPolicies[?PolicyArn==`'$ADDITIONAL_POLICY_ARN'`]' --output text | grep -q "$ADDITIONAL_POLICY_ARN"; then
            echo "✅ Policy already attached to role"
          else
            # Try to attach the additional permissions policy to CodeBuild role
            echo "Attempting to attach additional permissions to CodeBuild role..."
            if aws iam attach-role-policy --role-name "$CODEBUILD_ROLE_NAME" --policy-arn "$ADDITIONAL_POLICY_ARN"; then
              echo "✅ Successfully attached additional permissions policy"
              echo "⏳ Waiting 10 seconds for IAM permissions to propagate..."
              sleep 10
            else
              echo "❌ Failed to auto-attach policy. Manual attachment required:"
              echo "   aws iam attach-role-policy --role-name $CODEBUILD_ROLE_NAME --policy-arn $ADDITIONAL_POLICY_ARN"
              echo ""
              echo "Or attach via AWS Console:"
              echo "   IAM → Roles → $CODEBUILD_ROLE_NAME → Attach policies → Search: CodeBuildAdditionalPermissions-fb49b77e"
              exit 1
            fi
          fi
          
          # Store infrastructure outputs in SSM Parameter Store
          echo "Storing infrastructure outputs in SSM Parameter Store..."
          
          # Store API Gateway URL
          API_GATEWAY_ID=$(terraform -chdir=infra output -raw api_gateway_id)
          API_URL="https://${API_GATEWAY_ID}.execute-api.${AWS_DEFAULT_REGION}.amazonaws.com/dev/contact"
          if aws ssm put-parameter --name "/project3/api-gateway-url" --value "$API_URL" --type "String" --overwrite; then
            echo "✅ Stored API Gateway URL: $API_URL"
          else
            echo "❌ Failed to store API Gateway URL - check CodeBuild IAM permissions"
            echo "Required policy ARN: $(terraform -chdir=infra output -raw codebuild_additional_policy_arn)"
            exit 1
          fi
          
          # Store S3 bucket name
          S3_BUCKET=$(terraform -chdir=infra output -raw s3_bucket_name)
          if aws ssm put-parameter --name "/project3/s3-bucket" --value "$S3_BUCKET" --type "String" --overwrite; then
            echo "✅ Stored S3 Bucket: $S3_BUCKET"
          else
            echo "❌ Failed to store S3 bucket name"
            exit 1
          fi
          
          # Store CloudFront distribution ID
          CLOUDFRONT_ID=$(terraform -chdir=infra output -raw cloudfront_distribution_id)
          if aws ssm put-parameter --name "/project3/cloudfront-distribution-id" --value "$CLOUDFRONT_ID" --type "String" --overwrite; then
            echo "✅ Stored CloudFront Distribution ID: $CLOUDFRONT_ID"
          else
            echo "❌ Failed to store CloudFront distribution ID"
            exit 1
          fi
          
          # Store Lambda function name
          LAMBDA_NAME=$(terraform -chdir=infra output -raw lambda_function_name)
          if aws ssm put-parameter --name "/project3/lambda-function-name" --value "$LAMBDA_NAME" --type "String" --overwrite; then
            echo "✅ Stored Lambda Function Name: $LAMBDA_NAME"
          else
            echo "❌ Failed to store Lambda function name"
            exit 1
          fi
          
          echo "✅ Infrastructure deployment and SSM parameter storage completed!"
          
          # Create web pipeline (if it doesn't exist)
          echo "Creating web application pipeline..."
          if aws codepipeline get-pipeline --name project3-web-pipeline >/dev/null 2>&1; then
            echo "Web pipeline already exists, skipping creation"
          else
            echo "Creating new web pipeline..."
            
            # Get required values
            GITHUB_TOKEN=$(aws ssm get-parameter --name "/project3/github/token" --with-decryption --query 'Parameter.Value' --output text)
            ARTIFACTS_BUCKET=$(terraform -chdir=infra output -raw codepipeline_artifacts_bucket)
            PIPELINE_ROLE_ARN=$(terraform -chdir=infra output -raw codepipeline_role_arn)
            
            # Create pipeline JSON
            cat > web-pipeline.json << EOF
        {
          "pipeline": {
            "name": "project3-web-pipeline",
            "roleArn": "$PIPELINE_ROLE_ARN",
            "artifactStore": {
              "type": "S3",
              "location": "$ARTIFACTS_BUCKET"
            },
            "stages": [
              {
                "name": "Source",
                "actions": [
                  {
                    "name": "Source",
                    "actionTypeId": {
                      "category": "Source",
                      "owner": "ThirdParty",
                      "provider": "GitHub",
                      "version": "1"
                    },
                    "configuration": {
                      "Owner": "lerthy",
                      "Repo": "Project3_LS",
                      "Branch": "sibora-v2",
                      "OAuthToken": "$GITHUB_TOKEN",
                      "PollForSourceChanges": "false"
                    },
                    "outputArtifacts": [{"name": "source_output"}]
                  }
                ]
              },
              {
                "name": "Build",
                "actions": [
                  {
                    "name": "Build",
                    "actionTypeId": {
                      "category": "Build",
                      "owner": "AWS",
                      "provider": "CodeBuild",
                      "version": "1"
                    },
                    "configuration": {
                      "ProjectName": "project3-web-build"
                    },
                    "inputArtifacts": [{"name": "source_output"}]
                  }
                ]
              }
            ]
          }
        }
        EOF
            
            # Create the pipeline
            if aws codepipeline create-pipeline --cli-input-json file://web-pipeline.json; then
              echo "✅ Web pipeline created successfully!"
            else
              echo "❌ Failed to create web pipeline - check CodeBuild IAM permissions"
              echo "Required policy ARN: $(terraform -chdir=infra output -raw codebuild_additional_policy_arn)"
              exit 1
            fi
          fi
          
          # Trigger web pipeline after successful infrastructure deployment
          echo "Triggering web pipeline..."
          if aws codepipeline start-pipeline-execution --name project3-web-pipeline; then
            echo "✅ Web pipeline triggered successfully!"
          else
            echo "❌ Failed to trigger web pipeline - check CodeBuild IAM permissions"
            exit 1
          fi
        fi

artifacts:
  files:
    - 'infra/tfplan'
    - 'infra/coverage.out'
    - 'infra/terraform.tfstate'
    - 'web-pipeline.json'
  name: infra-artifacts

cache:
  paths:
    - 'infra/.terraform/**/*'
