version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm --prefix web install

  pre_build:
    commands:
      - echo "Pre-build phase"
      - echo "Running basic checks"

  build:
    commands:
      - echo "Build phase"
      - echo "Running tests"

  post_build:
    commands:
      - echo "Post-build phase"
      - echo "Deployment completed"