version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export AWS_DEFAULT_REGION=us-east-1 AWS_REGION=us-east-1
      # Install dependencies for web frontend
      - npm --prefix web ci || npm --prefix web install
      
      # Install dependencies for Lambda function
      - npm --prefix web/lambda ci || npm --prefix web/lambda install

  pre_build:
    commands:
      - echo "Running frontend quality checks..."
      
      # ESLint for JavaScript
      - npm --prefix web run lint:js
      
      # Stylelint for CSS
      - npm --prefix web run lint:css
      
      # ESLint for Lambda function
      - npm --prefix web/lambda run lint

  build:
    commands:
      - echo "Waiting 7 minutes before build steps..."
      - sleep 420
      - echo "Running tests..."
      
      # Frontend tests with coverage
      - npm --prefix web run test
      
      # Lambda tests with coverage
      - npm --prefix web/lambda run test
      
      - echo "Building static site..."
      # For this project, static files are already built
      # In a real Vite project, you'd run: npm run build

  post_build:
    commands:
      - echo "Deploying to S3 and updating Lambda..."
      
      # Get API Gateway URL dynamically
      - |
        echo "Fetching API Gateway URL..."
        API_GATEWAY_URL=$(aws apigateway get-rest-apis --query 'items[?name==`contact-api`].id' --output text)
        if [ -n "$API_GATEWAY_URL" ]; then
          API_GATEWAY_URL="https://${API_GATEWAY_URL}.execute-api.${AWS_DEFAULT_REGION}.amazonaws.com/dev/contact"
          echo "Using dynamically discovered API Gateway URL: $API_GATEWAY_URL"
        else
          echo "Error: Could not find contact-api REST API"
          exit 1
        fi
      
      # Replace API URL in config file
      - sed -i "s|{{API_GATEWAY_URL}}|$API_GATEWAY_URL|g" web/static/js/config.js
      
      # Deploy static files to S3
      - aws s3 sync web/static/ s3://$S3_BUCKET --delete
      
      # Package and deploy Lambda function (production-only dependencies)
      - cd web/lambda
      - mkdir -p deployment
      - cp index.js package.json deployment/
      - cd deployment
      - npm install --production
      - zip -r ../lambda-deployment.zip . -x "*.git*" "*.DS_Store*" "*node_modules/.cache*"
      - cd ..
      - aws lambda update-function-code --function-name contact-form --zip-file fileb://lambda-deployment.zip --region "$AWS_DEFAULT_REGION"
      - rm -rf deployment lambda-deployment.zip
      - cd ../..
      
      # Invalidate CloudFront cache
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - 'web/coverage/**/*'
    - 'web/lambda/coverage/**/*'
  name: web-artifacts

cache:
  paths:
    - 'web/node_modules/**/*'
    - 'web/lambda/node_modules/**/*'
