version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      # Install required packages (Amazon Linux uses yum)
      - yum update -y && yum install -y bc unzip wget
      
      # Install Terraform
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      
      # Install tflint
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      
      # Install Go dependencies for tests
      - go -C infra mod download

  pre_build:
    commands:
      - echo "Running Terraform quality checks..."
      
      # Terraform formatting check
      - terraform -chdir=infra fmt -recursive
      - terraform -chdir=infra fmt -check -recursive
      
      # Terraform validation (without backend)
      - terraform -chdir=infra init -backend=false
      - terraform -chdir=infra validate
      
      # TFLint
      - (cd infra && tflint --init)
      - (cd infra && tflint)

  build:
    commands:
      - echo "Running Terraform tests..."
      
      # Run unit tests with coverage (short mode to skip slow checks)
      - CI_SKIP_TERRATEST=1 go -C infra test -v -short -coverprofile=coverage.out ./tests/
      - go -C infra tool cover -func=coverage.out
      
      # Check coverage threshold (60%)
      - |
        COVERAGE=$(go -C infra tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Coverage: $COVERAGE%"
        if [ $(echo "$COVERAGE < 60" | bc -l) -eq 1 ]; then
          echo "Coverage $COVERAGE% is below required 60%"
          exit 1
        fi
        echo "Coverage $COVERAGE% meets requirement"

  post_build:
    commands:
      - echo "Running Terraform plan and apply..."
      
      # Create Lambda deployment package
      - (cd web/lambda && zip -r ../../infra/lambda.zip .)
      
      # Initialize Terraform backend (required for each phase)
      - terraform -chdir=infra init -reconfigure
      
      # Terraform plan
      - terraform -chdir=infra plan -out=tfplan
      
      # Terraform apply (only if not a PR)
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_CREATED" ] || [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_UPDATED" ]; then
          echo "Skipping apply for pull request"
        else
          # Apply Terraform
          terraform -chdir=infra apply -auto-approve tfplan
          
          # Store infrastructure outputs in SSM Parameter Store
          echo "Storing infrastructure outputs in SSM Parameter Store..."
          
          # Store API Gateway URL
          API_GATEWAY_ID=$(terraform -chdir=infra output -raw api_gateway_id)
          API_URL="https://${API_GATEWAY_ID}.execute-api.${AWS_DEFAULT_REGION}.amazonaws.com/dev/contact"
          if aws ssm put-parameter --name "/project3/api-gateway-url" --value "$API_URL" --type "String" --overwrite; then
            echo "✅ Stored API Gateway URL: $API_URL"
          else
            echo "⚠️  Warning: Could not store API Gateway URL (continuing anyway)"
          fi
          
          # Store S3 bucket name
          S3_BUCKET=$(terraform -chdir=infra output -raw s3_bucket_name)
          if aws ssm put-parameter --name "/project3/s3-bucket" --value "$S3_BUCKET" --type "String" --overwrite; then
            echo "✅ Stored S3 Bucket: $S3_BUCKET"
          else
            echo "⚠️  Warning: Could not store S3 bucket name (continuing anyway)"
          fi
          
          # Store CloudFront distribution ID
          CLOUDFRONT_ID=$(terraform -chdir=infra output -raw cloudfront_distribution_id)
          if aws ssm put-parameter --name "/project3/cloudfront-distribution-id" --value "$CLOUDFRONT_ID" --type "String" --overwrite; then
            echo "✅ Stored CloudFront Distribution ID: $CLOUDFRONT_ID"
          else
            echo "⚠️  Warning: Could not store CloudFront distribution ID (continuing anyway)"
          fi
          
          # Store Lambda function name
          LAMBDA_NAME=$(terraform -chdir=infra output -raw lambda_function_name)
          if aws ssm put-parameter --name "/project3/lambda-function-name" --value "$LAMBDA_NAME" --type "String" --overwrite; then
            echo "✅ Stored Lambda Function Name: $LAMBDA_NAME"
          else
            echo "⚠️  Warning: Could not store Lambda function name (continuing anyway)"
          fi
          
          echo "✅ Infrastructure deployment and SSM parameter storage completed!"
          
          # Ensure web pipeline is created and start it
          echo "🚀 Setting up web pipeline..."
          if aws codepipeline create-pipeline --cli-input-json file://web-pipeline.json 2>/dev/null; then
            echo "✅ Created web pipeline"
          elif aws codepipeline update-pipeline --cli-input-json file://web-pipeline.json 2>/dev/null; then
            echo "✅ Updated existing web pipeline"
          else
            echo "⚠️  Warning: Could not create/update web pipeline (might already exist)"
          fi
          
          # Start the web pipeline
          if aws codepipeline start-pipeline-execution --name project3-web-pipeline; then
            echo "✅ Started web pipeline execution"
          else
            echo "⚠️  Warning: Could not start web pipeline (check if it exists)"
          fi
          
          echo "🎉 Infrastructure deployment completed!"
          echo "📝 SSM parameters stored for web pipeline consumption"
          echo "🔄 Web pipeline execution initiated"

artifacts:
  files:
    - 'infra/tfplan'
    - 'infra/coverage.out'
    - 'infra/terraform.tfstate'
    - 'web-pipeline.json'
  name: infra-artifacts

cache:
  paths:
    - 'infra/.terraform/**/*'
