// API Configuration
// This file is dynamically generated by Terraform with the actual API Gateway URL and API key

window.API_CONFIG = {
  API_GATEWAY_URL: '${api_gateway_url}',
  API_KEY: '${api_key}',
};